### ISSUE TITLE
Massive amounts of server spam with Ratlantis

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/Better-Caves#88] opened 2020-11-10 01:14 UTC
I'm playing on my own private server, and anytime I visit the Ratlantis dimension the server starts spamming logs at a high rate. As soon as I return to the Overworld the log spam stops. Here's a snippet from one of my logs:

```
[08Nov2020 23:00:27.058] [Server-Worker-1066/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.125] [Server-Worker-1066/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.157] [Server-Worker-1066/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.195] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.225] [Server-Worker-1071/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.268] [Server-Worker-1070/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.325] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.358] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.381] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.406] [Server-Worker-1066/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.424] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.442] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.478] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.534] [Server-Worker-1073/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.560] [Server-Worker-1070/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.582] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.618] [Server-Worker-1071/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.693] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.826] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:27.988] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.004] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.021] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.040] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.065] [Server-Worker-1073/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.090] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.121] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.141] [Server-Worker-1071/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.161] [Server-Worker-1071/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.176] [Server-Worker-1071/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.192] [Server-Worker-1066/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.211] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.229] [Server-Worker-1066/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.259] [Server-Worker-1070/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.295] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.341] [Server-Worker-1066/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.361] [Server-Worker-1070/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.376] [Server-Worker-1071/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.407] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:28.437] [Server-Worker-1073/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.465] [Server-Worker-1070/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.482] [Server-Worker-1073/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.500] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.516] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.531] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.556] [Server-Worker-1070/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.571] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.585] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.600] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.619] [Server-Worker-1071/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.645] [Server-Worker-1073/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.717] [Server-Worker-1073/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.745] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.762] [Server-Worker-1070/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.778] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.794] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.820] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.834] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.849] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:53.864] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:54.148] [Server-Worker-1063/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:54.163] [Server-Worker-1067/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
[08Nov2020 23:00:54.177] [Server-Worker-1072/ERROR] [bettercaves/]: ERROR: Unable to get dimension name! Using default cave gen...
```

Minecraft 1.15.2
Forge 31.2.45
Better Caves 1.15.2-1.0 (default config)
Rats 5.3.2
Modpack: https://www.curseforge.com/minecraft/modpacks/the-new-adventure/files/3105776

**Comment by yungnickyoung** [comment] 2021-01-17 18:20
Sorry about this issue, I never got around to finding out the cause. Unfortunately I don't have time to support 1.15 anymore, so I'll be closing this issue. For active support, please either upgrade to 1.16 or downgrade to 1.12.

**Closed as completed by yungnickyoung** 2021-01-17 18:20 UTC
Labels: 1.15.2
