### ISSUE TITLE
Water caves under ocean biomes still generate with obsidian floor.

### ISSUE THREAD

**Issue by SatDog92** [yungnickyoung/Better-Caves#100] opened 2020-12-28 12:07 UTC
Forge version:  35.1.10. Mod version: 1.0.6

[This is above](https://user-images.githubusercontent.com/56725716/103210660-9f872e00-4906-11eb-813f-9527a3dc9308.png)
[and this is below](https://user-images.githubusercontent.com/56725716/103210663-a0b85b00-4906-11eb-8e18-e85de35f30f9.png). It's not really game breaking but it feels really weird and i don't think this should happen. I think these are just caves that replace lava with water at -11 but don't override the obsidian layer that usually generate underwater caves. The only solution here is disabling the feature but i wish this wasn't an issue.

On a related note, i also wish that caves generated under ocean biomes were also not flooded when not connected to the surface (as it happens with vanilla: caves connected to the ground underwater are flooded, the ones that aren't connected are dry) and that they didn't carve through bedrock when the flattening bedrock option is disabled (the noise is still there, but the bottom is still flattened).

Edit: just changed the title, i forgot to complete it.

**Comment by yungnickyoung** [comment] 2020-12-28 17:12
Duplicate of #72

**Closed as completed by yungnickyoung** 2020-12-28 17:12 UTC
Labels: duplicate
