### ISSUE TITLE
[1.16 Forge] Unsupported registration method causing crash

### ISSUE THREAD

**Issue by TheCurle** [yungnickyoung/Better-Caves#83] opened 2020-10-27 16:44 UTC
According to the following log provided by [a user](https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/82#issue-730013890): https://pastebin.com/GWbfFLxz

This line: https://github.com/yungnickyoung/YUNGs-Better-Caves/blob/1.16/src/main/java/com/yungnickyoung/minecraft/bettercaves/init/BCFeature.java#L32 

and many others, use Registry.register, which is unsupported in Forge.

Maybe event.register would work, but again, i do not have the time to look into this.

- Curle, Forge Triage

**Comment by yungnickyoung** [comment] 2020-10-27 17:59
Duplicate of #82

**Closed as completed by yungnickyoung** 2020-10-27 17:59 UTC
