### ISSUE TITLE
Modern Industrialization ores are floating around

### ISSUE THREAD

**Issue by Technici4n** [yungnickyoung/Better-Caves#87] opened 2020-11-10 00:28 UTC
Hello, when using Better Caves, Modern Industrialization's ores sometimes appear floating around.

![2020-11-10_01 01 07](https://user-images.githubusercontent.com/13494793/98610667-619b5f80-22f0-11eb-8903-ac8a62b7e1cb.png)

Steps to reproduce:
* Install Fabric on 1.16.4, grab latest Better Caves, Fabric API and Modern Industrialization.
* Create a new world, go to spectator mode and search a bit.

I am very surprised that this happens because Modern Industrialization just mixins into vanilla's `addDefaultOres` to register its ores...

**Comment by Technici4n** [comment] 2020-11-11 00:50
My bad, the features were registered in Bootstrap, but the blocks were registered in `initialize`. Registering the blocks before the features solved it!

**Comment by Technici4n** [comment] 2020-11-21 19:01
Reopening because this is actually a consequence of wrapping a carver in a feature...

**Comment by yungnickyoung** [comment] 2020-11-21 19:03
Duplicate of #56

**Closed as completed by yungnickyoung** 2020-11-21 19:03 UTC
