### ISSUE TITLE
Compatability Issues with Quark 

### ISSUE THREAD

**Issue by MCIcyChi** [yungnickyoung/Better-Caves#52] opened 2020-05-13 19:00 UTC
Hello Yung! I am just here to report to you issues with quarks cave root vines , and dungeon crawls dungeon generation. As you see in the images, the vines from quark are spawning in the air. 
![Cave Generation Glitch Quark](https://user-images.githubusercontent.com/65308715/81853122-0c8db500-952a-11ea-9ede-d11581e540b7.png)

**Comment by yungnickyoung** [comment] 2020-05-13 19:51
Hey, this is a duplicate of #49 . Vazkii fixed this in Quark-r2.1-236.
As for the Dungeon Crawl issue - please make a separate issue. Gonna close this one.

**Closed as completed by yungnickyoung** 2020-05-13 19:51 UTC
Labels: duplicate
