### ISSUE TITLE
hastebin not working- but game crashes on 1.12.2

### ISSUE THREAD

**Issue by MagicMaxcer** [yungnickyoung/Better-Caves#47] opened 2020-04-24 00:29 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  AstralCore (astralsorcery-1.12.2-1.10.23.jar)
  HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.10-core.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  ratscore (rats-3.2.9.jar)
  RandomPatches (randompatches-1.12.2-1.21.0.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  Max Potion ID Extender (maxpotidext-1.0.3.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 4/23/20 5:27 PM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at com.yungnickyoung.minecraft.bettercaves.world.ravine.MapGenBetterRavine.initialize(MapGenBetterRavine.java:90)
	at com.yungnickyoung.minecraft.bettercaves.world.ravine.MapGenBetterRavine.func_186125_a(MapGenBetterRavine.java:32)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:216)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:135)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.yungnickyoung.minecraft.bettercaves.world.ravine.MapGenBetterRavine.initialize(MapGenBetterRavine.java:90)
	at com.yungnickyoung.minecraft.bettercaves.world.ravine.MapGenBetterRavine.func_186125_a(MapGenBetterRavine.java:32)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:216)

-- Chunk to be generated --
Details:
	Location: 2,9
	Position hash: 38654705666
	Generator: net.minecraft.world.gen.ChunkGeneratorOverworld@7c504f9d
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: -3118200863299675850
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:135)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1251775720 bytes (1193 MB) / 3690987520 bytes (3520 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 162 mods loaded, 162 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version             | Source                                         | Signature                                |
	|:------ |:--------------------- |:------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2              | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                   | 9.42                | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                   | 8.0.99.99           | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | forge                 | 14.23.5.2847        | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | creativecoredummy     | 1.0.0               | minecraft.jar                                  | None                                     |
	| LCHIJA | itemphysic            | 1.4.0               | minecraft.jar                                  | None                                     |
	| LCHIJA | foamfixcore           | 7.7.4               | minecraft.jar                                  | None                                     |
	| LCHIJA | randompatches         | 1.12.2-1.21.0.2     | randompatches-1.12.2-1.21.0.2.jar              | None                                     |
	| LCHIJA | techguns_core         | 1.12.2-1.0          | minecraft.jar                                  | None                                     |
	| LCHIJA | deconstruction        | 3.0.4               | [MC1.12.2]DeconTable-3.0.4.jar                 | None                                     |
	| LCHIJA | jei                   | 4.15.0.291          | jei_1.12.2-4.15.0.291.jar                      | None                                     |
	| LCHIJA | abyssalcraft          | 1.9.18              | AbyssalCraft-1.12.2-1.9.18.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | aether_legacy         | 1.4.4               | aether_legacy-1.12.2-v1.4.4.jar                | None                                     |
	| LCHIJA | antiqueatlas          | 4.6.3               | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCHIJA | antiqueatlasoverlay   | 1.2                 | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCHIJA | aqua_creepers         | 1.2.3               | AquaCreepers-1.2.3.jar                         | None                                     |
	| LCHIJA | artemislib            | 1.0.6               | ArtemisLib-1.12.2-v1.0.6.jar                   | None                                     |
	| LCHIJA | baubles               | 1.5.2               | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | artifacts             | 1.12.2-1.1.0        | Artifacts-1.12.2-1.1.0.jar                     | None                                     |
	| LCHIJA | astralsorcery         | 1.10.22             | astralsorcery-1.12.2-1.10.23.jar               | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | attributefix          | 1.0.10              | AttributeFix-1.12.2-1.0.10.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | atum                  | 2.0.17              | Atum-1.12.2-2.0.17.jar                         | None                                     |
	| LCHIJA | autoreglib            | 1.3-32              | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHIJA | battletowers          | 1.6.5               | BattleTowers-1.12.2.jar                        | None                                     |
	| LCHIJA | beasts                | 1.2                 | Beasts-1.12.2-1.2.1.jar                        | None                                     |
	| LCHIJA | bettercaves           | 1.12.2              | bettercaves-1.12.2-2.0.jar                     | None                                     |
	| LCHIJA | forgelin              | 1.8.4               | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | betterfoliage         | 2.3.1               | BetterFoliage-MC1.12-2.3.1.jar                 | None                                     |
	| LCHIJA | betternether          | 0.1.8.6             | betternether-0.1.8.6.jar                       | None                                     |
	| LCHIJA | bonfires              | 1.2.2               | Bonfires-1.12.2-1.2.2-16eac59.jar              | None                                     |
	| LCHIJA | bookshelf             | 2.3.590             | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bookworm              | 1.12.2-2.5.1        | bookworm-1.12.2-2.5.1.jar                      | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26          | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| LCHIJA | botania               | r1.10-363           | Botania+r1.10-363.jar                          | None                                     |
	| LCHIJA | hammercore            | 2.0.6.14            | HammerLib-1.12.2-2.0.6.14.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | botanicadds           | 12.2.5              | BotanicAdditions-1.12.2-12.2.5.jar             | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | bountiful             | 2.2.1               | Bountiful-2.2.1.jar                            | None                                     |
	| LCHIJA | caliper               | 1.1.46              | Caliper-1.12.2-1.1.46.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | carryon               | 1.12.3              | CarryOn+MC1.12.2+v1.12.3.jar                   | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | chunkanimator         | 1.2                 | ChunkAnimator-MC1.12-1.2.jar                   | None                                     |
	| LCHIJA | clumps                | 3.1.2               | Clumps-3.1.2.jar                               | None                                     |
	| LCHIJA | combustfish           | 1.0.3.4             | combustfish-1.12.2-1.0.3.4.jar                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | cosmeticarmorreworked | 1.12.2-v5a          | CosmeticArmorReworked-1.12.2-v5a.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | tfmagic2              | 1.0.0               | Craftomancy-1.12.2-1.2.0.jar                   | None                                     |
	| LCHIJA | enhancedvisuals       | 1.3.0               | EnhancedVisuals_v1.3.11_mc1.12.2.jar           | None                                     |
	| LCHIJA | creativecore          | 1.10.0              | CreativeCore_v1.10.10_mc1.12.2.jar             | None                                     |
	| LCHIJA | crimsonwarfare        | 1.5                 | crimsonwarfare-1.5.jar                         | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCHIJA | cyclicmagic           | 1.20.2              | Cyclic-1.12.2-1.20.2.jar                       | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHIJA | dailies               | 1.12.2-6            | dailies-1.12.2-6.jar                           | None                                     |
	| LCHIJA | dimdoors              | 3.0.9+287           | DimensionalDoors-3.0.9-287.jar                 | None                                     |
	| LCHIJA | disenchanter          | 1.6                 | disenchanter-[1.12]1.6.jar                     | None                                     |
	| LCHIJA | doggytalents          | 1.15.1.5            | DoggyTalents-1.12.2-1.15.1.5.jar               | None                                     |
	| LCHIJA | dldungeonsjbg         | 1.13.1              | DoomlikeDungeons-1.13.1-MC1.12.2.jar           | None                                     |
	| LCHIJA | dungeonmobs           | 5.8.5               | dungeonmobs-5.8.5-MC1.12.2.jar                 | None                                     |
	| LCHIJA | dungeontactics        | DT-0.16.6           | DungeonTactics-1.12.2-0.16.6.jar               | None                                     |
	| LCHIJA | orelib                | 3.6.0.1             | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround             | 3.6.1.0             | DynamicSurroundings-1.12.2-3.6.1.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dynamictrees          | 1.12.2-0.9.7        | DynamicTrees-1.12.2-0.9.7.jar                  | None                                     |
	| LCHIJA | ebwizardry            | 4.2.11              | ElectroblobsWizardry-4.2.11-MC1.12.2.jar       | None                                     |
	| LCHIJA | mysticalmechanics     | 0.12                | Mystical+Mechanics-0.12.jar                    | None                                     |
	| LCHIJA | embers                | 1.13-hotfix2        | EmbersRekindled-1.13-hotfix2.jar               | None                                     |
	| LCHIJA | eplus                 | 5.0.176             | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | erebus                | 1.0.31              | Erebus-1.0.31.jar                              | None                                     |
	| LCHIJA | extrabotany           | 58                  | ExtraBotany-r1.1-58r.jar                       | None                                     |
	| LCHIJA | tekdrone              | 1.0.0               | EZDrones-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | fbp                   | 2.4.1               | FancyBlockParticles-1.12.x-2.4.1.jar           | None                                     |
	| LCHIJA | firstaid              | 1.6.13              | firstaid-1.6.14.jar                            | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | mod_lavacow           | 1.0.13              | Fishs_Undead_Rising-1.0.13.jar                 | None                                     |
	| LCHIJA | flying_things         | 1.5.2               | flying_things-1.5.2-1.12.jar                   | None                                     |
	| LCHIJA | foamfix               | 0.10.10-1.12.2      | foamfix-0.10.10-1.12.2.jar                     | None                                     |
	| LCHIJA | tschipplib            | 1.1.3               | TschippLib+MC1.12.2+v1.1.3.jar                 | None                                     |
	| LCHIJA | forgottenitems        | 1.2.1               | ForgottenItems+MC1.12.2+v1.2.1.jar             | None                                     |
	| LCHIJA | llibrary              | 1.7.19              | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil                | 8.0.3               | fossilsarcheology-8.0.3.jar                    | None                                     |
	| LCHIJA | gargoyles             | 1                   | Gargoyles+mod+1.12.2+patch+1.jar               | None                                     |
	| LCHIJA | gravestone            | 1.3.1               | GraveStone-1.12.2-Graves-1.3.1.jar             | None                                     |
	| LCHIJA | gravestone-extended   | 1.3.5.1             | GraveStone-1.12.2-Extended-1.3.5.1.jar         | None                                     |
	| LCHIJA | grimoireofgaia        | 1.7.2               | GrimoireOfGaia3-1.12.2-1.7.2.jar               | None                                     |
	| LCHIJA | harvestersnight       | 1.1.0               | harvestersnight-1.12.2-1.1.0.jar               | None                                     |
	| LCHIJA | iblis_headshots       | 1.2.6               | iblis-headshots-1.2.6.jar                      | None                                     |
	| LCHIJA | thaumadditions        | 12.4.2              | ThaumicAdditions-1.12.2-12.4.2.jar             | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | iceandfire            | 1.9.0               | iceandfire-1.9.0.jar                           | None                                     |
	| LCHIJA | infernalmobs          | 1.7.6               | InfernalMobs-1.12.2.jar                        | None                                     |
	| LCHIJA | inventorypets         | 2.0.3               | inventorypets-1.12-2.0.3.jar                   | None                                     |
	| LCHIJA | iymts_mob_mod         | 0.2.1               | iYAMATOs-Mob-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | iymts_mod             | 1.12.2-0.0.6        | iYAMATOs-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | jeresources           | 0.9.2.60            | JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
	| LCHIJA | lcrdrfs               | 2.0.0               | LaserCreeperRobotDinoRidersFromSpace-2.0.0.jar | None                                     |
	| LCHIJA | librarianlib          | 4.20                | librarianlib-1.12.2-4.20-release.jar           | None                                     |
	| LCHIJA | libraryex             | 1.1.1               | LibraryEx-1.12.2-1.1.1.jar                     | None                                     |
	| LCHIJA | lost_aether           | 0.1.3               | lost_aether-content-1.12.2-0.1.3.jar           | None                                     |
	| LCHIJA | lovely_robot          | 1.0.1               | LovelyRobot-1.12.2-1.0.1.jar                   | None                                     |
	| LCHIJA | lycanitesmobs         | 2.0.7.2 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.7.2.jar               | None                                     |
	| LCHIJA | mm                    | 0.3.4               | Maelstrom+Mod-0.3.4.jar                        | None                                     |
	| LCHIJA | magma_monsters        | 0.3.0               | MagmaMonsters-0.3.0.jar                        | None                                     |
	| LCHIJA | mahoutsukai           | 1.12.2-v1.15.15     | mahoutsukai-1.12.2-v1.15.15.jar                | None                                     |
	| LCHIJA | maxpotidext           | 1.0.3               | maxpotidext-1.0.3.jar                          | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCHIJA | megaloot              | 0.2.40              | megaloot-1.12.2-0.2.40.jar                     | None                                     |
	| LCHIJA | mirageorb             | 1.2.0               | mirageorb-1.12.2-1.2.0.jar                     | None                                     |
	| LCHIJA | mm_lib                | 1.2.0               | MMLib-1.2.0.jar                                | None                                     |
	| LCHIJA | mobends               | 0.24                | mobends-0.24_for_MC-1.12.jar                   | None                                     |
	| LCHIJA | mowziesmobs           | 1.5.4               | mowziesmobs-1.5.4.jar                          | None                                     |
	| LCHIJA | multimob              | 1.0.5               | multimob-1.0.5.jar                             | None                                     |
	| LCHIJA | mutantbeasts          | 1.12.2-0.7.1        | MutantBeasts-1.12.2-0.7.1.jar                  | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
	| LCHIJA | mmm                   | 1.0.8               | mutatedmobs-1.0.8.jar                          | None                                     |
	| LCHIJA | roots                 | 1.12.2-3.0.26       | Roots-1.12.2-3.0.26.jar                        | None                                     |
	| LCHIJA | mysticalworld         | 1.12.2-1.8.4        | mysticalworld-1.12.2-1.8.4.jar                 | None                                     |
	| LCHIJA | mystictools           | 1.6                 | mystictools-1.6.jar                            | None                                     |
	| LCHIJA | naturalpledge         | 3.0.3               | NaturalPledge-r3.1.2.jar                       | None                                     |
	| LCHIJA | netherex              | 2.1.5               | NetherEx-1.12.2-2.1.5.jar                      | None                                     |
	| LCHIJA | nmsot                 | 1.2.2-mc1.12.2      | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar        | None                                     |
	| LCHIJA | recipehandler         | 0.13                | NoMoreRecipeConflict-0.13(1.12.2).jar          | None                                     |
	| LCHIJA | neid                  | 1.5.4.4             | NotEnoughIDs-1.5.4.4.jar                       | None                                     |
	| LCHIJA | nyx                   | 1.3.0               | Nyx-1.3.0.jar                                  | None                                     |
	| LCHIJA | parry                 | 1.0                 | parry-1.0-hotfix.jar                           | None                                     |
	| LCHIJA | patchouli             | 1.0-20              | Patchouli-1.0-20.jar                           | None                                     |
	| LCHIJA | prehistoricspawns     | 1.0                 | prehistoricspawns-1.0.jar                      | None                                     |
	| LCHIJA | primitivemobs         | 1.2.3a              | primitivemobs-1.2.3a.jar                       | None                                     |
	| LCHIJA | psi                   | r1.1-77             | Psi-r1.1-77.jar                                | None                                     |
	| LCHIJA | pyramidplunder        | 1.12.2-1.0          | PyramidPlunder-1.12.2-1.4.jar                  | None                                     |
	| LCHIJA | rafradek_tf2_weapons  | 1.6.1               | rafradek_tf2_weapons-1.12.2-1.6.1.jar          | None                                     |
	| LCHIJA | randomloot            | 1.7.3               | randomloot+1.7.4.jar                           | None                                     |
	| LCHIJA | rats                  | 3.2.9               | rats-3.2.9.jar                                 | None                                     |
	| LCHIJA | xreliquary            | 1.12.2-1.3.4.796    | Reliquary-1.12.2-1.3.4.796.jar                 | None                                     |
	| LCHIJA | roguelike             | 2.1.1               | RoguelikeDungeonsFnarEdition-1.12.2-2.1.1.jar  | None                                     |
	| LCHIJA | rpsideas              | 2.4.2               | rpsideas-2.4.2.jar                             | None                                     |
	| LCHIJA | savemystronghold      | 1.12.2-1.0.0        | savemystronghold-1.12.2-1.0.0.jar              | None                                     |
	| LCHIJA | shipwrecks_winslow    | 2.0.0               | shipwrecks-mc1.12.2-2.0.0.jar                  | None                                     |
	| LCHIJA | flammpfeil.slashblade | mc1.12-r32          | SlashBlade-mc1.12-r32.jar                      | None                                     |
	| LCHIJA | slashblade_addon      | 1.4.0               | SJAP_V1.4.0_MC1.12.2.jar                       | None                                     |
	| LCHIJA | soundfilters          | 0.11_for_1.12       | SoundFilters-0.11_for_1.12.jar                 | None                                     |
	| LCHIJA | specialmobs           | 1.0.2_for_mc1.12.2  | specialmobs-1.0.2_for_mc1.12.2.jar             | None                                     |
	| LCHIJA | srparasites           | 1.7.0               | SRParasites-1.12.2v1.7.0.jar                   | None                                     |
	| LCHIJA | surge                 | 2.0.77              | Surge-1.12.2-2.0.77.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | switchbow             | 1.5.7               | switchbow-1.5.7.jar                            | None                                     |
	| LCHIJA | tameable_arachne      | 1.1.6               | tameable_arachne_mod-1.02.jar                  | None                                     |
	| LCHIJA | techguns              | 2.0.2.0             | techguns-1.12.2-2.0.2.0_pre3.1.jar             | None                                     |
	| LCHIJA | texfix                | 4.0                 | TexFix+V-1.12-4.0.jar                          | None                                     |
	| LCHIJA | twilightforest        | 3.10.1013           | twilightforest-1.12.2-3.10.1013-universal.jar  | None                                     |
	| LCHIJA | tfspellpack           | 1.0.1               | TFSpellPack-1.0.1-MC1.12.2.jar                 | None                                     |
	| LCHIJA | thaumicperiphery      | 0.3.1               | thaumicperiphery-0.3.1.jar                     | None                                     |
	| LCHIJA | lastsmith             | V1.2.6.5-MC1.12.2   | TLS-V1.2.6.5-MC1.12.2.jar                      | None                                     |
	| LCHIJA | tragicmc              | 0.51.4813-1.96      | TragicMC3-1.12.2-0.51.4813-1.96.jar            | None                                     |
	| LCHIJA | tumbleweed            | 1.12-0.4.7          | tumbleweed-1.12-0.4.7.jar                      | None                                     |
	| LCHIJA | uniquecrops           | 0.2.1               | uniquecrops-1.12.2-0.2.1.jar                   | None                                     |
	| LCHIJA | varodd                | 5.21                | varodd-1.12.2-5.21.jar                         | None                                     |
	| LCHIJA | veining               | 1.3.2               | veining-1.3.2-1.12.x.jar                       | None                                     |
	| LCHIJA | thejungle             | 1.2006.1222         | Welcome+To+The+Jungle-1.2006.1222.jar          | None                                     |
	| LCHIJA | wolfarmor             | 2.2.3.6             | wolfarmor-1.12.2-2.2.3.1798-universal.jar      | None                                     |
	| LCHIJA | worleycaves           | 1.5.1               | worleycaves-1.5.1.jar                          | None                                     |
	| LCHIJA | zawa                  | 1.12.2-2.0.2        | zawa-1.12.2-2.0.2.jar                          | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | betteranimalsplus     | 9.0.1               | betteranimalsplus-1.12.2-9.0.1.jar             | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0               | CraftStudio-1.0.1.95-mc1.12-alpha.jar          | None                                     |
	| LCHIJA | cyclopstek            | 1.0.34              | cyclopstek-1.0.34.jar                          | None                                     |
	| LCHIJA | immersiveengineering  | 0.12-92             | ImmersiveEngineering-0.12-92.jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | phosphor-lighting     | 1.12.2-0.2.6        | phosphor-1.12.2-0.2.6+build50-universal.jar    | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | thebetweenlands       | 3.5.10              | TheBetweenlands-3.5.10-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | totemexpansion        | 1.2.2               | totemexpansion-1.2.2-1.12.2.jar                | None                                     |
	| LCHIJA | worldsretold          | 1.0.7               | Worlds+Retold-+(v1.0.7)+14.23.5.2784.jar       | None                                     |
	| LCHIJA | librarianliblate      | 4.20                | librarianlib-1.12.2-4.20-release.jar           | None                                     |
	| LCHIJA | mysticallib           | 1.12.2-1.7.0        | mysticallib-1.12.2-1.7.0.jar                   | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
AstralCore (astralsorcery-1.12.2-1.10.23.jar)
  
HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.10-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
ratscore (rats-3.2.9.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
RandomPatches (randompatches-1.12.2-1.21.0.2.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
  
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
Max Potion ID Extender (maxpotidext-1.0.3.jar)
  zabi.minecraft.maxpotidext.MPIDTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	HammerCore Debug Information: 
Dependent Mods:
    -Botanic Additions (botanicadds) @12.2.5
    -Thaumic Additions: Reconstructed (thaumadditions) @12.4.2

	[Psi] Active spell: None
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.75
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by yungnickyoung** [comment] 2020-04-24 00:36
Duplicate of #46 . I'll try to have a fix out in the next few hours!

**Closed as completed by yungnickyoung** 2020-04-24 00:36 UTC
